### ISSUE TITLE
Not able to save a screenshot.

### ISSUE THREAD

**Issue by hgupta210** [BelAn97/mochawesome-screenshots#1]
Hi,

I am not able to save a screenshot using this mochawesome-sreenshot tool. below is the error I am getting-
Error: Unable to save screenshot
ReferenceError: path is not defined

Though the html report is created successfully but the failing screenshot is not there. Could you please check this and correct it.

conf.js file-

framework: 'mocha',

    mochaOpts: {
        grep: util.getGrep(),
        reporter: 'mochawesome-screenshots',
        reporterOptions: {
            reportTitle: util.getTitle(),
            inlineAssets: true            
        },
        timeout: 60000  /* --mochaOpts.timeout*/
    }

Thanks & Regards,
Hitesh Gupta

**Comment by BelAn97** [comment]
Please try the new version.
Regards, 
Andrei.

**Comment by kalaikaran** [comment]
Hi, 
    I am using mochawesome-screenshots the same way its been specified. Its generating an HTML report. But does not take any screenshorts. any suggestions ?
Thanks
kalaikaran K
