### ISSUE TITLE
Does mochawesome-screenshots support selenium webdriver? if yes, how should it be configured using .mocharc.js config file?

### ISSUE THREAD

**Issue by tvsatish9** [BelAn97/mochawesome-screenshots#33]

**Comment by BelAn97** [comment]
You can set 'browser' global variable as driver for taking screenshots.
Do not add 'framework' option or set it "framework=protractor"
.mocharc.js config example:
```
module.exports = {
  reporter: 'mochawesome-screenshots',
  reporterOptions: [
    "reportDir=customReportDir",
    "reportName=customReportName",
    "framework=protractor"
  ]
}
```

**Comment by tvsatish9** [comment]
i have declared 'browser' in 
export interface CustomNodeJsGlobal extends NodeJS.Global {
browser:any;
} 
and since i am already using a variable 'driver' to instantiate the driver object like below:
driver = new webdriver.Builder()
                        .forBrowser("chrome")
                        .build();

i added a line next saying:
global.browser = driver;

And my mocharc.js file is as below:
module.exports = {
    reporter: ['node_modules/mochawesome-screenshots'],
    'reporter-option': [
          'reportDir=reports',
          'reportName=Typescript',
          'reportTitle=Title typescript',
          'reportPageTitle=Page title Typescript',
          'takePassedScreenshot=false',
          'clearOldScreenshots=true',
          'shortScrFileNames=false',
          'jsonReport=false',
          'multiReport=false',
          'framework=protractor'
    ],
};

but i still not able to get any screenshot, even my test script failed.

**Comment by BelAn97** [comment]
For next simple test with your .mocharc.js config - all works fine.
```
    it('webdriver', async function() {
        require('chromedriver');
        const webdriver = require('selenium-webdriver');
        const driver = new webdriver.Builder()
            .forBrowser("chrome")
            .build();
        global.browser = driver;
        await driver.get('https:www.google.com');
        expect(1).eq(2);
    })
```

**Comment by tvsatish9** [comment]
@BelAn97 Thanks a lot for the help. I am not sure what was going wrong in my code, probably some cache issue with my IDE, i restarted my IDE and it worked fine for me now.

**Comment by BelAn97** [comment]
Great!
