### ISSUE TITLE
Screenshot names far too long

### ISSUE THREAD

**Issue by BrigJ** [BelAn97/mochawesome-screenshots#4]
I'm trying to use this reporter with protractor, Mocha and Yadda, running Gherkin features. 

Mochawesome works excellently with this setup, but the screenshot reporter does not, as when creating screenshots it creates the filename by combining the feature title, the scenario title and the step text, creating an enormous filename that is not accessible.

i.e.  If I had the Feature

```
Feature: I want to test a certain aspect of my web application

    Scenario:  When I do some stuff then some other stuff happen that is good

        Given I am using my app
        When I click some buttons or something in the prescribed manner
        Then stuff should happen
```

if the test fails on the 'When' step of this feature then the generated screenshot name will be:

I_want_to_test_a_certain_aspect_of_my_web_application_When_I_do_some_stuff_then_some_other_stuff_happen_that_is_good_When_I_click_some_buttons_or_something_in_the_prescribed_manner.png

Is there any way to shorten these names, or create custom names?  As it stands I can't use this reporter.

**Comment by BelAn97** [comment]
Fixed, try new version.

**Comment by BrigJ** [comment]
Awesome, thanks.
