### ISSUE TITLE
One Report for all Browsers

### ISSUE THREAD

**Issue by Jazz405** [BelAn97/mochawesome-screenshots#5]
Hola!

I'm working on different browsers, and would prefer that mochawesome would generate one report with the results for the different browsers instead of creating the report for each multiCapability. The report keeps overwriting itself. Maybe a flag such as --combineBrowsers?

**Comment by BelAn97** [comment]
Use option 'multiReport: true' to keep all parallel reports. It's impossible to combine them in one file.
