### ISSUE TITLE
Screenshots display

### ISSUE THREAD

**Issue by achaussier** [BelAn97/mochawesome-screenshots#6]
Hello,

First, thanks for your work !

I just check your project, and i've some issues with screenshots display.

Context:
* screenshot generate is OK, files exists,
* test with takePassedScreenshot set to true (same results with false also, but only second issue appear).
* node version: v6.3.0
* project version: 1.4.2
* I launch protractor into a Gulp task
* protractor version: "gulp-angular-protractor": "^0.1.4", "gulp-protractor": "^3.0.0",

Issues:
* For a success test, I've link to click on scresshot, but nothin appears. Here the code arroud the button:
`<p class="test-screenshot"><button class="btn btn-link btn-sm toggle-btn toggle-stack collapsed" data-toggle="collapse" data-target="#7c7a16b9-c156-447b-9afc-aa7db71f2b92 > .test-scr.collapse">Screenshot </button>
            </p>`
* For a failed test, no screenshot link appears

I've test with firefox, chrome, chormium, same issue.

Thanks

**Comment by BelAn97** [comment]
Hello!

Thank you for this issue!
Fixed at version 1.4.3.

Regards,
Andrei.

**Comment by achaussier** [comment]
Thanks, I confirm all is ok now
