### ISSUE TITLE
i can't see the passed screenshot

### ISSUE THREAD

**Issue by tony204** [BelAn97/mochawesome-screenshots#7]
i see the source code ,now it can't show the passed screenshot in the html, also i have already set the  "takePassedScreenshot": true

**Comment by BelAn97** [comment]
Could you show me your protractor config?

**Comment by tony204** [comment]
@BelAn97 
 "mocha": {
     "reporter": 'mochawesome-screenshots',
	  "reporterOptions": {
		  "reportDir": "../../report",
       "takePassedScreenshot": true,
       "clearOldScreenshots": true,
       "jsonReport": false
	    }

**Comment by tony204** [comment]
@BelAn97 

i saw in the source code  mochawesome.js, the generator on html  report only have the failed case, i can't found the pass case to include the png.


function cleanTest (test) {

  var err = test.err ? _.pick( test.err, ['name', 'message', 'expected', 'actual', 'stack', 'scr'] ) : test.err,
    scr = '<img src="./screenshots/' + test.title.replace(/ /g, '_').substr(0,process.env['MOCHAWESOME_MAXFILELENGHT']) + '.failed.png">';

**Comment by BelAn97** [comment]
Do you have passed screenshots files into you report folder? Do you have 'Show screenshot' link at reports passed tests?

**Comment by tony204** [comment]
@BelAn97  , i have the show screenshot link at reports passed tests , but didn't have the passed screenshots files in my report folder

**Comment by sumeetp4** [comment]
I'm using mocha, so I want to pass all the reporter options, how can I pass these using mocha.opts?
